[project]
name = "scry"
version = "0.1"
dependencies = [
  "requests",
  "pytest",
]
requires-python = ">= 3.12"
readme = "README.md"
authors = [
  { name="thrly", email="o.thrly@gmail.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

# defines the command and script that will be used to run
[project.scripts]
scry = "scry.main:main"

[project.urls]
repository = "https://github.com/thrly/scry"
issues = "https://github.com/thrly/scry/issues"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["scry*"]
